/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefRouteImport } from './routes/brief'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as MediaRouteImport } from './routes/media'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as SocialRouteImport } from './routes/social'
import { Route as VisibilityRouteImport } from './routes/visibility'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefRoute = BriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const VisibilityRoute = VisibilityRouteImport.update({
  id: '/visibility',
  path: '/visibility',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brief': typeof BriefRoute
  '/markets': typeof MarketsRoute
  '/media': typeof MediaRoute
  '/policy': typeof PolicyRoute
  '/signals': typeof SignalsRoute
  '/social': typeof SocialRoute
  '/visibility': typeof VisibilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brief': typeof BriefRoute
  '/markets': typeof MarketsRoute
  '/media': typeof MediaRoute
  '/policy': typeof PolicyRoute
  '/signals': typeof SignalsRoute
  '/social': typeof SocialRoute
  '/visibility': typeof VisibilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brief': typeof BriefRoute
  '/markets': typeof MarketsRoute
  '/media': typeof MediaRoute
  '/policy': typeof PolicyRoute
  '/signals': typeof SignalsRoute
  '/social': typeof SocialRoute
  '/visibility': typeof VisibilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brief'
    | '/markets'
    | '/media'
    | '/policy'
    | '/signals'
    | '/social'
    | '/visibility'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brief'
    | '/markets'
    | '/media'
    | '/policy'
    | '/signals'
    | '/social'
    | '/visibility'
  id:
    | '__root__'
    | '/'
    | '/brief'
    | '/markets'
    | '/media'
    | '/policy'
    | '/signals'
    | '/social'
    | '/visibility'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefRoute: typeof BriefRoute
  MarketsRoute: typeof MarketsRoute
  MediaRoute: typeof MediaRoute
  PolicyRoute: typeof PolicyRoute
  SignalsRoute: typeof SignalsRoute
  SocialRoute: typeof SocialRoute
  VisibilityRoute: typeof VisibilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief': {
      id: '/brief'
      path: '/brief'
      fullPath: '/brief'
      preLoaderRoute: typeof BriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visibility': {
      id: '/visibility'
      path: '/visibility'
      fullPath: '/visibility'
      preLoaderRoute: typeof VisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefRoute: BriefRoute,
  MarketsRoute: MarketsRoute,
  MediaRoute: MediaRoute,
  PolicyRoute: PolicyRoute,
  SignalsRoute: SignalsRoute,
  SocialRoute: SocialRoute,
  VisibilityRoute: VisibilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
